id: AC1C4FC8C
title: Prayer for the Long Life of Tulku Thondup Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:58:07.686808
  last_modified_at: 2022-03-01 01:58:07.686814
